# rundeck for compiling stand-alone version of GISS LSM
# coupled to Ent with FBB photosynthesis

# global objects to use:
OBJ_LIST = main_ent

# components to use:
COMPONENTS = Ent_standalone Ent shared

# specific options for components:
OPTS_Ent = PS_MODEL=FBB
#OPTS_giss_LSM = USE_ENT=YES
OPTS_shared =
#OPTS_giss_LSM_standalone = USE_ENT=YES

INPUT_FILES = \
VEG=$(GCMSEARCHPATH)/V72X46.1.cor2_no_crops.ext \
CROPS=$(GCMSEARCHPATH)/CROPS_72X46N.cor4.ext \
soil_textures=$(GCMSEARCHPATH)/soil_textures_top30cm \
SOILCARB_global=$(GCMSEARCHPATH)/soilcarb_top30cm_nmaps_4x5bin.dat \
CH=$(ENT_DATADIR)/CHJUN1950 \
DVIS=$(ENT_DATADIR)/DVISJUN1950 \
MP1=$(ENT_DATADIR)/MP1JUN1950 \
MP2=$(ENT_DATADIR)/MP2JUN1950 \
MP3=$(ENT_DATADIR)/MP3JUN1950 \
MP4=$(ENT_DATADIR)/MP4JUN1950 \
MP5=$(ENT_DATADIR)/MP5JUN1950 \
MP6=$(ENT_DATADIR)/MP6JUN1950 \
PREC=$(ENT_DATADIR)/PRECJUN1950 \
PS=$(ENT_DATADIR)/PSJUN1950 \
QFOL=$(ENT_DATADIR)/QFOLJUN1950 \
QLAT=$(ENT_DATADIR)/QLATJUN1950 \
QSEN=$(ENT_DATADIR)/QSENJUN1950 \
SAT=$(ENT_DATADIR)/SATJUN1950 \
SIC1=$(ENT_DATADIR)/SIC1JUN1950 \
SIC2=$(ENT_DATADIR)/SIC2JUN1950 \
SIC3=$(ENT_DATADIR)/SIC3JUN1950 \
SIC4=$(ENT_DATADIR)/SIC4JUN1950 \
SIC5=$(ENT_DATADIR)/SIC5JUN1950 \
SIC6=$(ENT_DATADIR)/SIC6JUN1950 \
TP=$(ENT_DATADIR)/TPJUN1950 \
US=$(ENT_DATADIR)/USJUN1950 \
VIS=$(ENT_DATADIR)/VISJUN1950 \
VS=$(ENT_DATADIR)/VSJUN1950 \
ZEN=$(ENT_DATADIR)/ZENJUN1950 \
SOILT1=$(ENT_DATADIR)/SOILT_dummy_1 \
SOILT2=$(ENT_DATADIR)/SOILT_dummy_2 \
SOILT3=$(ENT_DATADIR)/SOILT_dummy_3 \
SOILT4=$(ENT_DATADIR)/SOILT_dummy_4 \
SOILT5=$(ENT_DATADIR)/SOILT_dummy_5 \
SOILT6=$(ENT_DATADIR)/SOILT_dummy_6 \
W1=$(ENT_DATADIR)/SMOIST_dummy_1 \
W2=$(ENT_DATADIR)/SMOIST_dummy_2 \
W3=$(ENT_DATADIR)/SMOIST_dummy_3 \
W4=$(ENT_DATADIR)/SMOIST_dummy_4 \
W5=$(ENT_DATADIR)/SMOIST_dummy_5 \
W6=$(ENT_DATADIR)/SMOIST_dummy_6

RUN_PARAMETERS = \
&input_parameters \
year = 1998,jday=1, jday2=10, \
IM=72, JM=46, I0=40, I1=40, J0=39, J1=39, \
force_VEG=false, do_soilinit=true \
/
