# rundeck for compiling stand-alone version of GISS LSM
# coupled to Ent with FBB photosynthesis

OBJ_LIST=main_ent

# components to use:
COMPONENTS = Ent_standalone Ent shared

# specific options for components:
OPTS_Ent = PS_MODEL=FBB PFT_MODEL=ENT FLUXNET=YES
#OPTS_giss_LSM = USE_ENT=YES
OPTS_shared =
#OPTS_giss_LSM_standalone = USE_ENT=YES

DATADIR=/n/Moorcroft_Lab/Users/kim/ent-data/input-TNF

INPUT_FILES = \
VEG=$(DATADIR)/VEGCOV.TNF \
CROPS=$(DATADIR)/CROPS.TNF \
LAIent=$(DATADIR)/LAIent.TNF \
HITEent=$(DATADIR)/HITEent.TNF \
soil_textures=$(DATADIR)/soil_textures_top30cm.TNF \
SOILCARB_site=$(DATADIR)/SOILCARB_site_TNF.csv \
CH=$(DATADIR)/CH.TNF \
DVIS=$(DATADIR)/DVIS.TNF \
MP1=$(DATADIR)/MP1.TNF \
MP2=$(DATADIR)/MP2.TNF \
MP3=$(DATADIR)/MP3.TNF \
MP4=$(DATADIR)/MP4.TNF \
MP5=$(DATADIR)/MP5.TNF \
MP6=$(DATADIR)/MP6.TNF \
PREC=$(DATADIR)/PREC.TNF \
PS=$(DATADIR)/PS.TNF \
QFOL=$(DATADIR)/QFOL.TNF \
QLAT=$(DATADIR)/QLAT.TNF \
QSEN=$(DATADIR)/QSEN.TNF \
SAT=$(DATADIR)/SurfAirTC.TNF \
SIC1=$(DATADIR)/SIC1.TNF \
SIC2=$(DATADIR)/SIC2.TNF \
SIC3=$(DATADIR)/SIC3.TNF \
SIC4=$(DATADIR)/SIC4.TNF \
SIC5=$(DATADIR)/SIC5.TNF \
SIC6=$(DATADIR)/SIC6.TNF \
TP=$(DATADIR)/TcanC.TNF \
US=$(DATADIR)/US.TNF \
VIS=$(DATADIR)/VIS.TNF \
VS=$(DATADIR)/VS.TNF \
ZEN=$(DATADIR)/COSZEN.TNF \
SOILT1=$(DATADIR)/SOILT30cm.TNF \
SOILT2=$(DATADIR)/SOILT30cm.TNF \
SOILT3=$(DATADIR)/SOILT30cm.TNF \
SOILT4=$(DATADIR)/SOILT30cm.TNF \
SOILT5=$(DATADIR)/SOILT30cm.TNF \
SOILT6=$(DATADIR)/SOILT30cm.TNF \
W1=$(DATADIR)/SMOIST30cm.TNF \
W2=$(DATADIR)/SMOIST30cm.TNF \
W3=$(DATADIR)/SMOIST30cm.TNF \
W4=$(DATADIR)/SMOIST30cm.TNF \
W5=$(DATADIR)/SMOIST30cm.TNF \
W6=$(DATADIR)/SMOIST30cm.TNF \
LAI1=$(DATADIR)/LAI1.TNF \
LAI2=$(DATADIR)/LAI2.TNF \
LAI3=$(DATADIR)/LAI3.TNF \
LAI4=$(DATADIR)/LAI4.TNF \
LAI5=$(DATADIR)/LAI5.TNF \
LAI6=$(DATADIR)/LAI6.TNF \
LAI7=$(DATADIR)/LAI7.TNF \
LAI8=$(DATADIR)/LAI8.TNF \
LAI9=$(DATADIR)/LAI9.TNF \
LAI10=$(DATADIR)/LAI10.TNF \
LAI11=$(DATADIR)/LAI11.TNF \
LAI12=$(DATADIR)/LAI12.TNF \
LAI13=$(DATADIR)/LAI13.TNF \
LAI14=$(DATADIR)/LAI14.TNF \
LAI15=$(DATADIR)/LAI15.TNF \
LAI16=$(DATADIR)/LAI16.TNF \
HEIGHT1=$(DATADIR)/heightm1.TNF \
HEIGHT2=$(DATADIR)/heightm2.TNF \
HEIGHT3=$(DATADIR)/heightm3.TNF \
HEIGHT4=$(DATADIR)/heightm4.TNF \
HEIGHT5=$(DATADIR)/heightm5.TNF \
HEIGHT6=$(DATADIR)/heightm6.TNF \
HEIGHT7=$(DATADIR)/heightm7.TNF \
HEIGHT8=$(DATADIR)/heightm8.TNF \
HEIGHT9=$(DATADIR)/heightm9.TNF \
HEIGHT10=$(DATADIR)/heightm10.TNF \
HEIGHT11=$(DATADIR)/heightm11.TNF \
HEIGHT12=$(DATADIR)/heightm12.TNF \
HEIGHT13=$(DATADIR)/heightm13.TNF \
HEIGHT14=$(DATADIR)/heightm14.TNF \
HEIGHT15=$(DATADIR)/heightm15.TNF \
HEIGHT16=$(DATADIR)/heightm16.TNF 

RUN_PARAMETERS = \
&input_parameters \
year=2001,jday=91,jday2=90,year2=2003,dt=3600.0, \
IM=72,JM=46,I0=26,I1=26,J0=23,J1=23,I0f=26,I1f=26,J0f=23,J1f=23, \
force_VEG=.false., \
do_soilinit=.true., \
do_phenology_activegrowth=.true.,\
do_structuralgrowth=.true.,\
do_frost_hardiness=.false.,\
do_spinup=.true.\
/
